all:
  vars:
    ansible_connection: ssh
    security_mode: plaintext
zookeeper:
  hosts:
    NRGL-CORE-MPP-m-5:
    NRGL-CORE-MPP-m-7:
    NRGL-CORE-MPP-o-7:
broker:
  hosts:
    NRGL-CORE-MPP1-a-6:
      kafka:
        broker:
          id: 1
    NRGL-CORE-MPP1-a-8:
      kafka:
        broker:
          id: 2
    NRGL-CORE-MPP1-a-9:
      kafka:
        broker:
          id: 3
    NRGL-CORE-MPP-r-10:
      kafka:
        broker:
          id: 4
    NRGL-CORE-MPP-r-11:
      kafka:
        broker:
          id: 5
    NRGL-CORE-MPP-r-12:
      kafka:
        broker:
          id: 6
    NRGL-CORE-MPP-r-5:
      kafka:
        broker:
          id: 7
    NRGL-CORE-MPP-r-8:
      kafka:
        broker:
          id: 8
    NRGL-CORE-MPP-u-10:
      kafka:
        broker:
          id: 9
    NRGL-CORE-MPP-u-15:
      kafka:
        broker:
          id: 10
    NRGL-CORE-MPP-u-8:
      kafka:
        broker:
          id: 11
    NRGL-CORE-MPP-v-11:
      kafka:
        broker:
          id: 12
    NRGL-CORE-MPP-v-12:
      kafka:
        broker:
          id: 13
    NRGL-CORE-MPP-v-13:
      kafka:
        broker:
          id: 14
    NRGL-CORE-MPP-v-14:
      kafka:
        broker:
          id: 15
    NRGL-CORE-MPP-v-15:
      kafka:
        broker:
          id: 16
    NRGL-CORE-MPP-v-4:
      kafka:
        broker:
          id: 17
    NRGL-CORE-MPP-v-5:
      kafka:
        broker:
          id: 18
    NRGL-CORE-MPP-v-7:
      kafka:
        broker:
          id: 19
    NRGL-CORE-MPP-w-1:
      kafka:
        broker:
          id: 20
    NRGL-CORE-MPP-w-13:
      kafka:
        broker:
          id: 21
    NRGL-CORE-MPP-w-2:
      kafka:
        broker:
          id: 22
    NRGL-CORE-MPP-w-3:
      kafka:
        broker:
          id: 23
    NRGL-CORE-MPP-w-5:
      kafka:
        broker:
          id: 24
    NRGL-CORE-MPP-x-10:
      kafka:
        broker:
          id: 25
    NRGL-CORE-MPP-x-14:
      kafka:
        broker:
          id: 26