- name: broker group
  group:
    name: "{{kafka.broker.group}}"
- name: broker user
  user:
    name: "{{kafka.broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka.broker.group}}"
- name: create broker data directories
  file:
    path: "{{item}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0755
  with_items: "{{kafka.broker.datadir}}"
- name: distribute Kafka dist
  unarchive:
    src: "{{role_path}}/dist/{{kafka.broker.dist_file}}"
    dest: "{{kafka.broker.dist_dir}}"
- name: move Kafka to home dir
  shell: "mv {{kafka.broker.dist_dir}}/kafka_* {{kafka.broker.home}}"
  args:
    executable: /bin/bash
- name: change kafka home owership to kafka user
  file:
    path: "{{kafka.broker.home}}"
    recurse: yes
    state: directory
    mode: 0755
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
- name: broker plaintext config
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "plaintext"

- name: create systemd file
  template:
    src: environment.j2
    dest: "{{kafka.broker.systemd_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  notify:
    - reload systemd
    - restart kafka
- name: broker configure service
  systemd:
    name: "{{kafka.broker.service_name}}"
    enabled: "{{kafka.broker.systemd.enabled}}"
    state: "{{kafka.broker.systemd.state}}"